export const LIST_EXPERIENCE = 'LIST_EXPERIENCE'
export const LIST_EXPERIENCE_PENDING = `${LIST_EXPERIENCE}_PENDING`
export const LIST_EXPERIENCE_FULFILLED = `${LIST_EXPERIENCE}_FULFILLED`
export const LIST_EXPERIENCE_REJECTED = `${LIST_EXPERIENCE}_REJECTED`
