export const LIST_CANDIDACY = 'LIST_CANDIDACY'
export const LIST_CANDIDACY_PENDING = `${LIST_CANDIDACY}_PENDING`
export const LIST_CANDIDACY_FULFILLED = `${LIST_CANDIDACY}_FULFILLED`
export const LIST_CANDIDACY_REJECTED = `${LIST_CANDIDACY}_REJECTED`

export const RETRIEVE_COUNTER_CANDIDACY = 'RETRIEVE_COUNTER_CANDIDACY'
export const RETRIEVE_COUNTER_CANDIDACY_PENDING = `${RETRIEVE_COUNTER_CANDIDACY}_PENDING`
export const RETRIEVE_COUNTER_CANDIDACY_FULFILLED = `${RETRIEVE_COUNTER_CANDIDACY}_FULFILLED`
export const RETRIEVE_COUNTER_CANDIDACY_REJECTED = `${RETRIEVE_COUNTER_CANDIDACY}_REJECTED`

export const RETRIEVE_CANDIDACY = 'RETRIEVE_CANDIDACY'
export const RETRIEVE_CANDIDACY_PENDING = `${RETRIEVE_CANDIDACY}_PENDING`
export const RETRIEVE_CANDIDACY_FULFILLED = `${RETRIEVE_CANDIDACY}_FULFILLED`
export const RETRIEVE_CANDIDACY_REJECTED = `${RETRIEVE_CANDIDACY}_REJECTED`

export const LIST_COMMENTS_CANDIDACY = 'LIST_COMMENTS_CANDIDACY'
export const LIST_COMMENTS_CANDIDACY_PENDING = `${LIST_COMMENTS_CANDIDACY}_PENDING`
export const LIST_COMMENTS_CANDIDACY_FULFILLED = `${LIST_COMMENTS_CANDIDACY}_FULFILLED`
export const LIST_COMMENTS_CANDIDACY_REJECTED = `${LIST_COMMENTS_CANDIDACY}_REJECTED`

export const NEXT_COMMENTS_CANDIDACY = 'NEXT_COMMENTS_CANDIDACY'
export const NEXT_COMMENTS_CANDIDACY_PENDING = `${NEXT_COMMENTS_CANDIDACY}_PENDING`
export const NEXT_COMMENTS_CANDIDACY_FULFILLED = `${NEXT_COMMENTS_CANDIDACY}_FULFILLED`
export const NEXT_COMMENTS_CANDIDACY_REJECTED = `${NEXT_COMMENTS_CANDIDACY}_REJECTED`

export const CREATE_COMMENT_CANDIDACY = 'CREATE_COMMENT_CANDIDACY'
export const CREATE_COMMENT_CANDIDACY_PENDING = `${CREATE_COMMENT_CANDIDACY}_PENDING`
export const CREATE_COMMENT_CANDIDACY_FULFILLED = `${CREATE_COMMENT_CANDIDACY}_FULFILLED`
export const CREATE_COMMENT_CANDIDACY_REJECTED = `${CREATE_COMMENT_CANDIDACY}_REJECTED`

export const UPDATE_STATUS_CANDIDACY = 'UPDATE_STATUS_CANDIDACY'
export const UPDATE_STATUS_CANDIDACY_PENDING = `${UPDATE_STATUS_CANDIDACY}_PENDING`
export const UPDATE_STATUS_CANDIDACY_FULFILLED = `${UPDATE_STATUS_CANDIDACY}_FULFILLED`
export const UPDATE_STATUS_CANDIDACY_REJECTED = `${UPDATE_STATUS_CANDIDACY}_REJECTED`
