export const LIST_STUDY_LEVEL = 'LIST_STUDY_LEVEL'
export const LIST_STUDY_LEVEL_PENDING = `${LIST_STUDY_LEVEL}_PENDING`
export const LIST_STUDY_LEVEL_FULFILLED = `${LIST_STUDY_LEVEL}_FULFILLED`
export const LIST_STUDY_LEVEL_REJECTED = `${LIST_STUDY_LEVEL}_REJECTED`
