export const LIST_CONTRACT_TYPE = 'LIST_CONTRACT_TYPE'
export const LIST_CONTRACT_TYPE_PENDING = `${LIST_CONTRACT_TYPE}_PENDING`
export const LIST_CONTRACT_TYPE_FULFILLED = `${LIST_CONTRACT_TYPE}_FULFILLED`
export const LIST_CONTRACT_TYPE_REJECTED = `${LIST_CONTRACT_TYPE}_REJECTED`
