export const LIST_RESUME = 'LIST_RESUME'
export const LIST_RESUME_PENDING = `${LIST_RESUME}_PENDING`
export const LIST_RESUME_FULFILLED = `${LIST_RESUME}_FULFILLED`
export const LIST_RESUME_REJECTED = `${LIST_RESUME}_REJECTED`

export const RETRIEVE_RESUME = 'RETRIEVE_RESUME'
export const RETRIEVE_RESUME_PENDING = `${RETRIEVE_RESUME}_PENDING`
export const RETRIEVE_RESUME_FULFILLED = `${RETRIEVE_RESUME}_FULFILLED`
export const RETRIEVE_RESUME_REJECTED = `${RETRIEVE_RESUME}_REJECTED`

export const EXISTS_CANDIDACY_RESUME = 'EXISTS_CANDIDACY_RESUME'
export const EXISTS_CANDIDACY_RESUME_PENDING = `${EXISTS_CANDIDACY_RESUME}_PENDING`
export const EXISTS_CANDIDACY_RESUME_FULFILLED = `${EXISTS_CANDIDACY_RESUME}_FULFILLED`
export const EXISTS_CANDIDACY_RESUME_REJECTED = `${EXISTS_CANDIDACY_RESUME}_REJECTED`
