export const RETRIEVE_PRO = 'RETRIEVE_PRO'
export const RETRIEVE_PRO_PENDING = `${RETRIEVE_PRO}_PENDING`
export const RETRIEVE_PRO_FULFILLED = `${RETRIEVE_PRO}_FULFILLED`
export const RETRIEVE_PRO_REJECTED = `${RETRIEVE_PRO}_REJECTED`

export const CREATE_PRO = 'CREATE_PRO'
export const CREATE_PRO_PENDING = `${CREATE_PRO}_PENDING`
export const CREATE_PRO_FULFILLED = `${CREATE_PRO}_FULFILLED`
export const CREATE_PRO_REJECTED = `${CREATE_PRO}_REJECTED`

export const UPDATE_PRO = 'UPDATE_PRO'
export const UPDATE_PRO_PENDING = `${UPDATE_PRO}_PENDING`
export const UPDATE_PRO_FULFILLED = `${UPDATE_PRO}_FULFILLED`
export const UPDATE_PRO_REJECTED = `${UPDATE_PRO}_REJECTED`
