export const LIST_JOB = 'LIST_JOB'
export const LIST_JOB_PENDING = `${LIST_JOB}_PENDING`
export const LIST_JOB_FULFILLED = `${LIST_JOB}_FULFILLED`
export const LIST_JOB_REJECTED = `${LIST_JOB}_REJECTED`

export const RETRIEVE_JOB = 'RETRIEVE_JOB'
export const RETRIEVE_JOB_PENDING = `${RETRIEVE_JOB}_PENDING`
export const RETRIEVE_JOB_FULFILLED = `${RETRIEVE_JOB}_FULFILLED`
export const RETRIEVE_JOB_REJECTED = `${RETRIEVE_JOB}_REJECTED`

export const RETRIEVE_COUNTER_JOB = 'RETRIEVE_COUNTER_JOB'
export const RETRIEVE_COUNTER_JOB_PENDING = `${RETRIEVE_COUNTER_JOB}_PENDING`
export const RETRIEVE_COUNTER_JOB_FULFILLED = `${RETRIEVE_COUNTER_JOB}_FULFILLED`
export const RETRIEVE_COUNTER_JOB_REJECTED = `${RETRIEVE_COUNTER_JOB}_REJECTED`

export const CREATE_JOB = 'CREATE_JOB'
export const CREATE_JOB_PENDING = `${CREATE_JOB}_PENDING`
export const CREATE_JOB_FULFILLED = `${CREATE_JOB}_FULFILLED`
export const CREATE_JOB_REJECTED = `${CREATE_JOB}_REJECTED`

export const UPDATE_JOB = 'UPDATE_JOB'
export const UPDATE_JOB_PENDING = `${UPDATE_JOB}_PENDING`
export const UPDATE_JOB_FULFILLED = `${UPDATE_JOB}_FULFILLED`
export const UPDATE_JOB_REJECTED = `${UPDATE_JOB}_REJECTED`

export const DESTROY_JOB = 'DESTROY_JOB'
export const DESTROY_JOB_PENDING = `${DESTROY_JOB}_PENDING`
export const DESTROY_JOB_FULFILLED = `${DESTROY_JOB}_FULFILLED`
export const DESTROY_JOB_REJECTED = `${DESTROY_JOB}_REJECTED`

export const PUBLISH_JOB = 'PUBLISH_JOB'
export const PUBLISH_JOB_PENDING = `${PUBLISH_JOB}_PENDING`
export const PUBLISH_JOB_FULFILLED = `${PUBLISH_JOB}_FULFILLED`
export const PUBLISH_JOB_REJECTED = `${PUBLISH_JOB}_REJECTED`

export const LIST_INVITATION_EMAIL = 'LIST_INVITATION_EMAIL'
export const LIST_INVITATION_EMAIL_PENDING = `${LIST_INVITATION_EMAIL}_PENDING`
export const LIST_INVITATION_EMAIL_FULFILLED = `${LIST_INVITATION_EMAIL}_FULFILLED`
export const LIST_INVITATION_EMAIL_REJECTED = `${LIST_INVITATION_EMAIL}_REJECTED`

export const CREATE_INVITATION_EMAIL = 'CREATE_INVITATION_EMAIL'
export const CREATE_INVITATION_EMAIL_PENDING = `${CREATE_INVITATION_EMAIL}_PENDING`
export const CREATE_INVITATION_EMAIL_FULFILLED = `${CREATE_INVITATION_EMAIL}_FULFILLED`
export const CREATE_INVITATION_EMAIL_REJECTED = `${CREATE_INVITATION_EMAIL}_REJECTED`
