export const LIST_COLLABORATOR = 'LIST_COLLABORATOR'
export const LIST_COLLABORATOR_PENDING = `${LIST_COLLABORATOR}_PENDING`
export const LIST_COLLABORATOR_FULFILLED = `${LIST_COLLABORATOR}_FULFILLED`
export const LIST_COLLABORATOR_REJECTED = `${LIST_COLLABORATOR}_REJECTED`

export const CREATE_COLLABORATOR = 'CREATE_COLLABORATOR'
export const CREATE_COLLABORATOR_PENDING = `${CREATE_COLLABORATOR}_PENDING`
export const CREATE_COLLABORATOR_FULFILLED = `${CREATE_COLLABORATOR}_FULFILLED`
export const CREATE_COLLABORATOR_REJECTED = `${CREATE_COLLABORATOR}_REJECTED`

export const DESTROY_COLLABORATOR = 'DESTROY_COLLABORATOR'
export const DESTROY_COLLABORATOR_PENDING = `${DESTROY_COLLABORATOR}_PENDING`
export const DESTROY_COLLABORATOR_FULFILLED = `${DESTROY_COLLABORATOR}_FULFILLED`
export const DESTROY_COLLABORATOR_REJECTED = `${DESTROY_COLLABORATOR}_REJECTED`
