export const LIST_EMPLOYEE = 'LIST_EMPLOYEE'
export const LIST_EMPLOYEE_PENDING = `${LIST_EMPLOYEE}_PENDING`
export const LIST_EMPLOYEE_FULFILLED = `${LIST_EMPLOYEE}_FULFILLED`
export const LIST_EMPLOYEE_REJECTED = `${LIST_EMPLOYEE}_REJECTED`
