export const LIST_JOB_QUESTION = 'LIST_JOB_QUESTION'
export const LIST_JOB_QUESTION_PENDING = `${LIST_JOB_QUESTION}_PENDING`
export const LIST_JOB_QUESTION_FULFILLED = `${LIST_JOB_QUESTION}_FULFILLED`
export const LIST_JOB_QUESTION_REJECTED = `${LIST_JOB_QUESTION}_REJECTED`

export const UPDATE_JOB_QUESTION = 'UPDATE_JOB_QUESTION'
export const UPDATE_JOB_QUESTION_PENDING = `${UPDATE_JOB_QUESTION}_PENDING`
export const UPDATE_JOB_QUESTION_FULFILLED = `${UPDATE_JOB_QUESTION}_FULFILLED`
export const UPDATE_JOB_QUESTION_REJECTED = `${UPDATE_JOB_QUESTION}_REJECTED`
