export const LIST_INDUSTRY = 'LIST_INDUSTRY'
export const LIST_INDUSTRY_PENDING = `${LIST_INDUSTRY}_PENDING`
export const LIST_INDUSTRY_FULFILLED = `${LIST_INDUSTRY}_FULFILLED`
export const LIST_INDUSTRY_REJECTED = `${LIST_INDUSTRY}_REJECTED`
